[advisories]
version = 2
yanked = "deny"
ignore = [
    # This is temporary. See avbroot's deny.toml.
    "RUSTSEC-2023-0071",
]

[licenses]
version = 2
include-dev = true
allow = [
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-3-Clause",
    "bzip2-1.0.6",
    "GPL-3.0-only",
    "ISC",
    "LGPL-2.1-or-later",
    "MIT",
    "Unicode-3.0",
    "Zlib",
]

[bans]
multiple-versions = "warn"
multiple-versions-include-dev = true
deny = [
    # https://github.com/serde-rs/serde/issues/2538
    { name = "serde_derive", version = ">=1.0.172,<1.0.184" },
]

[bans.build]
executables = "deny"
include-dependencies = true
include-workspace = true
bypass = [
    # Only used in tests.
    { name = "libloading", allow-globs = ["tests/nagisa*.dll"] },
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-git = [
    "https://github.com/chenxiaolong/avbroot",
    "https://github.com/chenxiaolong/sepatch",
    "https://github.com/chenxiaolong/system-properties",
]
