[package]
name = "custota-tool"
license.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
anyhow = "1.0.75"
ring = "0.17.14"
clap = { version = "4.4.1", features = ["derive"] }
# Waiting for stable release that's compatible with the rest of the newer
# RustCrypto dependencies.
cms = { git = "https://github.com/RustCrypto/formats", rev = "c478c6bb0db65677e85e2c0297962817eed90352", features = ["std", "builder"] }
const-oid = "0.10.2"
ctrlc = "3.4.5"
hex = "0.4.3"
md5 = "0.8.0"
rawzip = "0.5.1"
rsa = { version = "0.10.0-rc.18", features = ["sha1", "sha2"] }
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.105"
serde_repr = "0.1.19"
sha2 = "0.11.0"
tracing = "0.1.41"
x509-cert = "0.3.0"
tempfile = "3.20.0"

[dependencies.avbroot]
git = "https://github.com/chenxiaolong/avbroot"
tag = "v3.32.0"

[build-dependencies]
anyhow = "1.0.75"
